"""
email_sender.py — SMTP email sender for PhishGuard AI.
Sends generated phishing simulation emails to a real inbox
for live detection testing. Educational use only.
"""

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart


def detect_smtp_server(email_addr):
    """Auto-detect SMTP server from email domain."""
    domain = email_addr.split("@")[-1].lower()
    smtp_map = {
        "gmail.com": ("smtp.gmail.com", 587),
        "googlemail.com": ("smtp.gmail.com", 587),
        "outlook.com": ("smtp-mail.outlook.com", 587),
        "hotmail.com": ("smtp-mail.outlook.com", 587),
        "live.com": ("smtp-mail.outlook.com", 587),
        "msn.com": ("smtp-mail.outlook.com", 587),
        "yahoo.com": ("smtp.mail.yahoo.com", 587),
        "yahoo.co.uk": ("smtp.mail.yahoo.com", 587),
        "ymail.com": ("smtp.mail.yahoo.com", 587),
        "icloud.com": ("smtp.mail.me.com", 587),
        "me.com": ("smtp.mail.me.com", 587),
        "mac.com": ("smtp.mail.me.com", 587),
        "aol.com": ("smtp.aol.com", 587),
        "protonmail.com": ("smtp.protonmail.ch", 587),
        "proton.me": ("smtp.protonmail.ch", 587),
        "zoho.com": ("smtp.zoho.com", 587),
        "gmx.com": ("smtp.gmx.com", 587),
        "mail.com": ("smtp.mail.com", 587),
    }
    return smtp_map.get(domain, (f"smtp.{domain}", 587))



def send_email(
    sender_email,
    sender_password,
    recipient_email,
    subject,
    body_html,
    display_name=None,
    smtp_server=None,
    smtp_port=None,
):
    """
    Send an email via SMTP.

    Args:
        sender_email:    The authenticated sender's real email address.
        sender_password: App password for the sender account.
        recipient_email: Where to deliver the email.
        subject:         Email subject line.
        body_html:       HTML body content.
        display_name:    Optional display name shown in the From header.
        smtp_server:     Optional SMTP host override.
        smtp_port:       Optional SMTP port override.

    Returns:
        dict with {success, message_id, error}
    """
    # Auto-detect server if not provided
    if not smtp_server:
        smtp_server, default_port = detect_smtp_server(sender_email)
        smtp_port = smtp_port or default_port
    smtp_port = smtp_port or 587

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        from_header = f"{display_name} <{sender_email}>" if display_name else sender_email
        msg["From"] = from_header
        msg["To"] = recipient_email
        msg["X-PhishGuard"] = "SIMULATION — Educational Security Training"

        # Plain text fallback
        plain = f"[PhishGuard AI Simulation]\n\nSubject: {subject}\n\n(This email is an HTML simulation. View in an HTML-capable email client.)"
        msg.attach(MIMEText(plain, "plain"))

        # HTML body — wrap with a simulation banner
        wrapped_html = f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body>
{body_html}
<hr style="margin-top:40px;border:none;border-top:2px solid #ef4444;">
<div style="padding:12px;background:#1a1a2e;color:#94a3b8;font-size:11px;font-family:monospace;text-align:center;border-radius:6px;margin-top:8px;">
⚠️ This email was generated by <strong style="color:#38bdf8;">PhishGuard AI</strong> for security awareness training.
It is a <strong style="color:#f87171;">simulated phishing email</strong> — no malicious intent.
</div>
</body>
</html>"""
        msg.attach(MIMEText(wrapped_html, "html"))

        # Connect and send
        server = smtplib.SMTP(smtp_server, smtp_port, timeout=15)
        server.ehlo()
        server.starttls()
        server.ehlo()
        server.login(sender_email, sender_password)
        server.sendmail(sender_email, recipient_email, msg.as_string())
        message_id = msg.get("Message-ID", "sent")
        server.quit()

        return {
            "success": True,
            "message_id": message_id,
            "error": None,
        }

    except smtplib.SMTPAuthenticationError:
        return {
            "success": False,
            "message_id": None,
            "error": "Authentication failed. For Gmail, use an App Password (not your regular password). Go to Google Account → Security → App Passwords.",
        }
    except smtplib.SMTPException as e:
        return {
            "success": False,
            "message_id": None,
            "error": f"SMTP error: {str(e)}",
        }
    except OSError as e:
        # Covers socket.gaierror (DNS) and connection refused
        if "getaddrinfo" in str(e) or "11001" in str(e):
            return {
                "success": False,
                "message_id": None,
                "error": f"Could not connect to SMTP server '{smtp_server}'. Make sure you're using a real email address from a supported provider (Gmail, Outlook, Yahoo, iCloud, etc.).",
            }
        return {
            "success": False,
            "message_id": None,
            "error": f"Connection error: {str(e)}",
        }
    except Exception as e:
        return {
            "success": False,
            "message_id": None,
            "error": f"Send failed: {str(e)}",
        }
